Add docs, tweak usage
- cert is always required, so make a positional arg
- switch to unconfined snap, because otherwise it errors with

PermissionError: [Errno 13] Permission denied: '/usr/lib/ssl/certs/ca-certificates.crt'